"""empty message

Revision ID: 1904967b3635
Revises: 14dd14c7de34
Create Date: 2023-11-16 14:16:41.473371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1904967b3635'
down_revision = '14dd14c7de34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.drop_column('receiver_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receiver_id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
