"""Initial migration after reset

Revision ID: 380d921d5ed9
Revises: 
Create Date: 2024-08-24 01:30:15.907802

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '380d921d5ed9'
down_revision = None
branch_labels = None
depends_on = None

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")

def upgrade():
    op.create_table('projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('project_name', sa.String(length=40), nullable=False),
        sa.Column('project_type', sa.String(), nullable=False),
        sa.Column('image_url', sa.String(length=255), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('body', sa.Text(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('image_url', sa.String(length=255), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=40), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    op.create_table('comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('comment_content', sa.Text(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_requests',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sender_id', sa.Integer(), nullable=True),
        sa.Column('receiver_id', sa.Integer(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message_content', sa.Text(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_projects',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('post_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
     # Add foreign key constraints
    op.create_foreign_key(None, 'posts', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'join_requests', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'join_requests', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'join_requests', 'users', ['receiver_id'], ['id'])
    op.create_foreign_key(None, 'join_requests', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'project_messages', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'project_messages', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_projects', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'user_projects', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'user_projects', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE comments SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE join_requests SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE posts SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE project_messages SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE projects SET SCHEMA {SCHEMA};")

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_projects')
    op.drop_table('project_messages')
    op.drop_table('join_requests')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
